### PR TITLE
Add missing semigroup instances

### PR DESCRIPTION
**Pull request by larskuhtz**
Makes the library compile with GHC 8.4

### CODE REVIEW

**Comment by dsorokin** [comment]
Thanks Lars for pointing to the issue with new GHC 8.4. I'll consider your patch soon.

Best regards,
David Sorokin

**Comment by dsorokin** [comment]
Hi! I receive compilation errors like this:

**Comment by larskuhtz** [comment]
Oops, yes, `(<>)` has conflicting definitions in previous versions of base. I think, `(<>)` must be either hidden in the import of `Data.Monoid` or, the import of `Data.Monoid` can be omitted at all, since, `Data.Semigroup` redefines or reexport most of it. But there are some inconsistencies in the definition of instances for `Last` and `First`, so the later does not always work.

I'll take a look and update the PR.

**Comment by dsorokin** [comment]
Please no need in travis. I test manually

**Comment by larskuhtz** [comment]
I am happy, to remove the travis file when this PR is ready to go in. I don't have a setup for testing older versions of GHC locally, so I use it for testing this PR.

**Comment by dsorokin** [comment]
Please remake your pull request for new branch feature/ghc-8-4-support by including the first two commits only (without travis). I will resolve the compilation issues myself. Please do the same for aivika-transformers as well. 

P.S. It is easy to repeat the commits by using command `git cherry-pick <commit-hash>` in the desired branch. I could do it myself, but I don't see your commits in my own repository.
